using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Umbraco.Cms.SourceGenerators;

/// <summary>
///     Roslyn incremental source generator that discovers all non-abstract classes
///     inheriting from <c>Umbraco.Cms.Core.HealthChecks.HealthCheck</c> in the current
///     compilation and emits an assembly-level
///     <c>Umbraco.Cms.Core.HealthChecks.GeneratedHealthChecksAttribute</c> for each one.
/// </summary>
/// <remarks>
///     The generated attributes are collected at startup by
///     <c>UmbracoBuilderExtensions.AddAllCoreCollectionBuilders</c>, eliminating the need
///     for a full assembly reflection scan to register built-in health checks.
/// </remarks>
[Generator]
public sealed class HealthCheckSourceGenerator : IIncrementalGenerator
{
    private const string HealthCheckFullName = "Umbraco.Cms.Core.HealthChecks.HealthCheck";
    private const string AttributeFullName = "Umbraco.Cms.Core.HealthChecks.GeneratedHealthChecksAttribute";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Collect all class declarations up front (syntax-only, fast).
        IncrementalValueProvider<ImmutableArray<ClassDeclarationSyntax>> classDeclarations =
            context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => s is ClassDeclarationSyntax,
                    transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
                .Collect();

        // Combine with the full compilation so we can do semantic analysis.
        IncrementalValueProvider<(Compilation, ImmutableArray<ClassDeclarationSyntax>)> compilationAndClasses =
            context.CompilationProvider.Combine(classDeclarations);

        context.RegisterSourceOutput(compilationAndClasses, static (spc, source) =>
            Execute(spc, source.Item1, source.Item2));
    }

    private static void Execute(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<ClassDeclarationSyntax> classes)
    {
        // Resolve the HealthCheck base-class symbol.
        INamedTypeSymbol? healthCheckSymbol = compilation.GetTypeByMetadataName(HealthCheckFullName);
        if (healthCheckSymbol is null)
        {
            // The target assembly does not reference Umbraco.Core — nothing to generate.
            return;
        }

        // Resolve the attribute symbol; it must exist (declared in Umbraco.Core).
        INamedTypeSymbol? attributeSymbol = compilation.GetTypeByMetadataName(AttributeFullName);
        if (attributeSymbol is null)
        {
            return;
        }

        // Find all concrete (non-abstract, non-generic) HealthCheck subclasses defined
        // *in this compilation* (not in referenced assemblies — those have their own generated files).
        var healthCheckTypes = new List<INamedTypeSymbol>();
        foreach (ClassDeclarationSyntax classDecl in classes)
        {
            SemanticModel semanticModel = compilation.GetSemanticModel(classDecl.SyntaxTree);
            if (semanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol symbol)
            {
                continue;
            }

            if (symbol.IsAbstract || symbol.IsGenericType)
            {
                continue;
            }

            if (InheritsFrom(symbol, healthCheckSymbol))
            {
                healthCheckTypes.Add(symbol);
            }
        }

        if (healthCheckTypes.Count == 0)
        {
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Umbraco.Cms.SourceGenerators.HealthCheckSourceGenerator.");
        sb.AppendLine("// Do not edit this file manually.");
        sb.AppendLine();

        // Emit one assembly-level attribute per discovered HealthCheck type.
        // Sorting by full name makes the output deterministic across builds.
        foreach (INamedTypeSymbol type in healthCheckTypes.OrderBy(t => t.ToDisplayString()))
        {
            sb.Append("[assembly: global::");
            sb.Append(AttributeFullName);
            sb.Append("(typeof(global::");
            sb.Append(type.ToDisplayString());
            sb.AppendLine("))]");
        }

        context.AddSource("HealthCheckRegistrations.g.cs", sb.ToString());
    }

    private static bool InheritsFrom(INamedTypeSymbol symbol, INamedTypeSymbol baseSymbol)
    {
        INamedTypeSymbol? current = symbol.BaseType;
        while (current is not null)
        {
            if (SymbolEqualityComparer.Default.Equals(current, baseSymbol))
            {
                return true;
            }

            current = current.BaseType;
        }

        return false;
    }
}
